import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Playfair_Display } from "next/font/google";
import { ScreenSizeProvider } from "@/providers/ScreenSizeProvider";
import { MountProvider } from "@/providers/MountProvider";
import Header from "@/layouts/header/Header";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["900"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${playfairDisplay.variable} antialiased w-screen overflow-x-hidden`}
      >
        <ScreenSizeProvider>
          <MountProvider>
            <Header />
            {children}
          </MountProvider>
        </ScreenSizeProvider>
      </body>
    </html>
  );
}
